export const TYPES = {
    AuthService: Symbol('AuthService'),
    ValidationService: Symbol('ValidationService'),
    TokenService: Symbol('TokenService'),
    GoogleVerificationService: Symbol('GooGoogleVerificationService'),
    OtpService: Symbol('OtpService'),
    PaymentService: Symbol('PaymentService'),
    ChatService: Symbol('ChatService'),
    SocketService: Symbol('SocketService'),
    AdminAuthService: Symbol('AdminAuthService'),
    MentorOnboardService: Symbol('MentorOnboardService'),
    NotificationService: Symbol('NotificationService'),
    AdminService: Symbol('AdminService'),
    PasswordService: Symbol('PasswordService'),
    MentorAuthService: Symbol('MentorAuthService'),
    MentorService: Symbol('MentorService'),

    AdminRepository: Symbol('AdminRepository'),
    UserRepository: Symbol('UserRepository'),
    MentorRepository: Symbol('MentorRepository'),
    UnverifiedUserRepository: Symbol('UnverifiedUserRepository'),
    ChatRepository: Symbol('ChatRepository'),
    MessageRepository: Symbol('MessageRepository'),
    NotificationRepository: Symbol('NotificationRepository'),

    AdminController: Symbol('AdminController'),
    UserController: Symbol('UserController'),
    MentorController: Symbol('MentorController'),
    PaymentController: Symbol('paymentController'),
    ChatController: Symbol('chatController'),
    SocketController: Symbol('SocketController'),
    MentorOnboardController: Symbol('MentorOnboardController'),
    PlannerTaskService: Symbol('PlannerTaskService'),
    PlannerTaskRepository: Symbol('PlannerTaskRepository'),
    PlannerTaskController: Symbol('PlannerTaskController'),

    MentorshipService: Symbol('MentorshipService'),
    WalletService: Symbol('WalletService'),
    MentorshipRepository: Symbol('MentorshipRepository'),
    WalletRepository: Symbol('WalletRepository'),
    MentorshipController: Symbol('MentorshipController'),
    NotificationController: Symbol('NotificationController'),
};
