export const TYPES = {
    AuthService: Symbol('AuthService'),
    ValidationService: Symbol('ValidationService'),
    TokenService: Symbol('TokenService'),
    GoogleVerificationService: Symbol('GooGoogleVerificationService'),
    OtpService: Symbol('OtpService'),
    PaymentService: Symbol('PaymentService'),
    ChatService: Symbol('ChatService'),
    SocketService: Symbol('SocketService'),
    AdminAuthService: Symbol('AdminAuthService'),
    MentorOnboardService: Symbol('MentorOnboardService'),
    NotificationService: Symbol('NotificationService'),
    AdminService: Symbol('AdminService'),
    PasswordService: Symbol('PasswordService'),
    MentorAuthService: Symbol('MentorAuthService'),
    MentorService: Symbol('MentorService'),
    PomodoroService: Symbol('PomodoroService'),
    PlannerTaskService: Symbol('PlannerTaskService'),
    MentorshipService: Symbol('MentorshipService'),
    WalletService: Symbol('WalletService'),
    KanbanService: Symbol('KanbanService'),
    BadgeService : Symbol('BadgeService'),
    PlanService: Symbol('PlanService'),
    NoteService: Symbol('NoteService'),
    DailyStreakCalculator: Symbol('DailyStreakCalculator'),
    TaskGamificationHandler: Symbol('TaskGamificationHandler'),
    IBadgeEvaluator: Symbol('IBadgeEvaluator'),
    IGamificationHandleService : Symbol('IGamificationHandleService'),
    BadgeTemplateResolverService: Symbol('BadgeTemplateResolverService'),
    BadgeGamficationService:Symbol('BadgeGamficationService'),
    
    AdminRepository: Symbol('AdminRepository'),
    UserRepository: Symbol('UserRepository'),
    MentorRepository: Symbol('MentorRepository'),
    UnverifiedUserRepository: Symbol('UnverifiedUserRepository'),
    ChatRepository: Symbol('ChatRepository'),
    MessageRepository: Symbol('MessageRepository'),
    NotificationRepository: Symbol('NotificationRepository'),
    PomodoroRepository: Symbol('PomodoroRepository'),
    MentorshipRepository: Symbol('MentorshipRepository'),
    WalletRepository: Symbol('WalletRepository'),
    KanbanRepository: Symbol('KanbanRepository'),
    BadgeRepository: Symbol('BadgeRepository'),
    planRepository:Symbol('planRepository'),
    UserStatsRepository: Symbol('UserStatsRepository'),
    UserBadgeRepository : Symbol('UserBadgeRepository'),
    

    AdminController: Symbol('AdminController'),
    UserController: Symbol('UserController'),
    MentorController: Symbol('MentorController'),
    PaymentController: Symbol('paymentController'),
    ChatController: Symbol('chatController'),
    SocketController: Symbol('SocketController'),
    MentorOnboardController: Symbol('MentorOnboardController'),
    PlannerTaskRepository: Symbol('PlannerTaskRepository'),
    PlannerTaskController: Symbol('PlannerTaskController'),
    PomodoroController: Symbol('PomodoroController'),
    WalletController: Symbol('WalletController'),
    MentorshipController: Symbol('MentorshipController'),
    NoteController: Symbol('NoteController'),
    PlanController: Symbol('PlanController'),
    
    NoteRepository: Symbol('NoteRepository'),
    BookingRepository: Symbol('BookingRepository'),
    BookingService: Symbol('BookingService'),
    BookingController: Symbol('BookingController'),

    GamificationController: Symbol('GamificationController'),
    BadgeController : Symbol('BadgeController'),
    ReviewService: Symbol('ReviewService'),
    ReviewRepository: Symbol('ReviewRepository'),
    ReviewController: Symbol('ReviewController'),
};
