export const TYPES = {
    AuthService: Symbol('AuthService'),
    ValidationService: Symbol('ValidationService'),
    TokenService: Symbol('TokenService'),
    GoogleVerificationService: Symbol('GooGoogleVerificationService'),
    OtpService: Symbol('OtpService'),
    PaymentService: Symbol('PaymentService'),
    ChatService: Symbol('ChatService'),
    SocketService: Symbol('SocketService'),
    KanbanService: Symbol('KanbanService'),
    AdminAuthService: Symbol('AdminAuthService'),
    MentorOnboardService: Symbol('MentorOnboardService'),
    NotificationService: Symbol('NotificationService'),
    AdminService: Symbol('AdminService'),
    PasswordService: Symbol('PasswordService'),

    AdminRepository: Symbol('AdminRepository'),
    UserRepository: Symbol('UserRepository'),
    MentorRepository: Symbol('MentorRepository'),
    UnverifiedUserRepository: Symbol('UnverifiedUserRepository'),
    ChatRepository: Symbol('ChatRepository'),
    MessageRepository: Symbol('MessageRepository'),
    KanbanRepository: Symbol('KanbanRepository'),
    NotificationRepository: Symbol('NotificationRepository'),

    AdminController: Symbol('AdminController'),
    UserController: Symbol('UserController'),
    MentorController: Symbol('MentorController'),
    PaymentController: Symbol('paymentController'),
    ChatController: Symbol('chatController'),
    SocketController: Symbol('SocketController'),
    KanbanController: Symbol('KanbanController'),
    MentorOnboardController: Symbol('MentorOnboardController'),
};
